# Generated by Django 5.0.4 on 2024-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_commentmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
