# Generated by Django 5.0.4 on 2024-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cars Available'),
        ),
    ]
