# Generated by Django 5.0.4 on 2024-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='detail',
            field=models.TextField(default='Sorry ', null=True, verbose_name='Details'),
        ),
    ]
