# Generated by Django 5.0.4 on 2024-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmodel_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='owner',
            field=models.CharField(default=None, max_length=100, verbose_name='Car Woner'),
        ),
    ]
