# Generated by Django 5.0.4 on 2024-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='owner',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Car Woner'),
        ),
    ]
