# Generated by Django 5.0.4 on 2024-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Woner'),
        ),
    ]
